<@createFile fileName="README.md">
This file is automatically generated by Fuml Studio.
Do not modify generated files - YOUR CHANGES WILL BE ERASED!

List of classes:
<#list model.allClasses as class>
${class.name}
</#list>

</@createFile>